# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-14 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('melliapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produkt',
            old_name='nazwa',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='produkt',
            old_name='opis',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='produkt',
            old_name='cena',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='produkt',
            old_name='wymiary',
            new_name='size',
        ),
    ]
