# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-15 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import melliapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('melliapp', '0002_auto_20180214_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='melliapp/static/images'),
        ),
    ]
