# Generated by Django 2.0.2 on 2018-03-17 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('melliapp', '0004_auto_20180215_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produkt',
            old_name='photo',
            new_name='photo1',
        ),
        migrations.RenameField(
            model_name='produkt',
            old_name='size',
            new_name='size1',
        ),
        migrations.AddField(
            model_name='produkt',
            name='color1',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='produkt',
            name='color2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='produkt',
            name='color3',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='produkt',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='melliapp/static/images'),
        ),
        migrations.AddField(
            model_name='produkt',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='melliapp/static/images'),
        ),
        migrations.AddField(
            model_name='produkt',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='melliapp/static/images'),
        ),
        migrations.AddField(
            model_name='produkt',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='melliapp/static/images'),
        ),
        migrations.AddField(
            model_name='produkt',
            name='size2',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produkt',
            name='size3',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
